version: "3.3"
services:
  web:
    image: syzoj/syzoj-ng:latest
    restart: always
    ports:
      - "5000:80"
    networks:
      - syzoj-ng-net
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./data:/data
    environment:
      RABBITMQ_ERLANG_COOKIE: syzoj
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: syzoj
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/data
  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: syzoj
networks:
  syzoj-ng-net:
    driver: bridge
volumes:
  data:
  redis:
